"""userid

Revision ID: 14de940b0ea6
Revises: a385654469c0
Create Date: 2025-02-10 11:18:24.280654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14de940b0ea6'
down_revision: Union[str, None] = 'a385654469c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['user_uid'], ['uid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_uid')
    # ### end Alembic commands ###
