"""location

Revision ID: 5970620d4c15
Revises: 176f48333b95
Create Date: 2025-02-14 18:10:00.285094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5970620d4c15'
down_revision: Union[str, None] = '176f48333b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('bookings', 'dropoff_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'dropoff_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bookings', 'location')
    # ### end Alembic commands ###
