"""email

Revision ID: a5dbde0b11aa
Revises: 0438e4a3cb24
Create Date: 2025-02-13 09:32:36.952314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5dbde0b11aa'
down_revision: Union[str, None] = '0438e4a3cb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'client_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('client_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
